#  Copyright (C) 2013 Free Software Foundation, Inc.
#
#  Author: Ivan Vucica <ivan@vucica.net>
#
#  This file is part of the GNUstep Backend.
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; see the file COPYING.LIB.
#  If not, see <http://www.gnu.org/licenses/> or write to the 
#  Free Software Foundation, 51 Franklin Street, Fifth Floor, 
#  Boston, MA 02110-1301, USA.

PACKAGE_NAME = gnustep-ai

SUBPROJECT_NAME=fuzzy

# The Objective-C source files to be compiled
fuzzy_OBJC_FILES = OpalFuzzyDB.m \
 OpalFuzzy.m \
 OpalFuzzyManipulator.m \
 OpalFuzzyMatrix.m \
 OpalFuzzyNetwork.m \
 OpalFuzzyNode.m \
 OpalFuzzyPaintParser.m \
 OpalFuzzyPaintRules.m \
 OpalFuzzyPaintRuleSystem.m \
 OpalFuzzyParser.m \
 OpalFuzzyPredicate.m \


-include GNUmakefile.preamble

-include GNUmakefile.postamble

